//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.21 at 03:04:32 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.car.com/car")
package com.example.monolitna.soap.wsdl;
